spring:
  datasource:
    url: jdbc:sqlite:${user.home}/.e-patra/file_metadata.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

app:
  backup-folder: "backups/"
